#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define FRUIT_SCORE_FIRST_5_SECOND 500
#define FRUIT_SCORE_LAST_3_SECOND 200
#define SCORE_POINT 10
#define DISPLAY_TIME_SPLASH_SCENE 1
#define DISPLAY_TIME_ABOUT_SCENE 6
#define TRANSITION_TIME 0.5
#define UPDATE_TIME 1
#define PLAYER_NORMAL_SPEED 1
#define PLAYER_ACTIVE_SPEED 1
#define GHOST_NORMAL_SPEED 1
#define GHOST_ACTIVE_SPEED 3

#endif // DEFINITIONS_H
