#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define DISPLAY_TIME_SPLASH_SCENE 1
#define TRANSITION_TIME 0.5
#define UPDATE_TIME 2
#define PLAYER_NORMAL_SPEED 10
#define PLAYER_ACTIVE_SPEED 12
#define GHOST_NORMAL_SPEED 11
#define GHOST_ACTIVE_SPEED 13

#endif // DEFINITIONS_H
