#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define DISPLAY_TIME_SPLASH_SCENE 1
#define TRANSITION_TIME 0.5
#define UPDATE_TIME 2
#define PLAYER_NORMAL_SPEED 0.2
#define PLAYER_ACTIVE_SPEED 2
#define GHOST_NORMAL_SPEED 1
#define GHOST_ACTIVE_SPEED 3

#endif // DEFINITIONS_H
